{'turn right':'Rotate right',
 'turn left':'Rotate left',
 'go straight':'Go forward',
 'go back':'Go back',
 'look at me':'Yes',
 'start ggi learning':'Start ggi learning',
 'follow me':'I will follow you',
 'stop following':'Stop following',
 'finish voice control':'Goodbye',
 'start map creating':'Start map creation',
 'append location name':'Please tell me the location name',
 'save location':'Please tell me the file name',
 'save map':'Save map',
 'hey mimi':'Yes, master',
 'what time is it':"It's",
 'what is the date today':"It's",
 'i have a message':'OK',
 'start happy time':"I'm MickeyMouse!"}
