{'turn right':'motion',
 'turn left':'motion',
 'go straight':'motion',
 'go back':'motion',
 'look at me':'motion',
 'start ggi learning':'learn',
 'follow me':'event',
 'stop following':'event',
 'finish voice_control':'stask',
 'start map creating':'event',
 'append location name':'learn',
 'save location':'learn',
 'save map':'learn',
 'hey mimi':'event',
 'what time is it':'stask',
 'what is the date today':'stask',
 'i have a message':'stask',
 'start happy time':'stask'}
