{'turn_right':'motion',
 'turn_left':'motion',
 'go_straight':'motion',
 'go_back':'motion',
 'look_here':'motion',
 'start_ggi_learning':'learn',
 'start_follow':'event',
 'stop_follow':'event',
 'finish_voice_control':'stask',
 'start_map_creating':'event',
 'add_location':'learn',
 'save_location':'learn',
 'save_map':'learn',
 'hey_mimi':'event',
 'what_time_is_it':'stask',
 'what_is_the_date_today':'stask',
 'i_have_a_message':'stask'}
