{'turn right':'motion',
 'turn left':'motion',
 'go straight':'motion',
 'go back':'motion',
 'follow me':'motion',
 'stop following':'motion',
 'finish voice control':'event',
 'what time is it':'event',
 'what is the date today':'event',
 'i have a message':'event',
 'start happy time':'event',
 'start navigation':'event'}
